# Generated by Django 5.1.5 on 2025-01-28 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=255)),
                ('referral_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('vendorkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField()),
                ('customer_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.customervendor')),
            ],
        ),
    ]
