# Generated by Django 4.2 on 2025-01-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=255)),
                ('vendorkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.vendor')),
            ],
        ),
    ]
